[versions]
agp = "8.9.0"
androidMapsUtils = "3.4.0"
androidxJunitVersion = "1.1.5"
constraintlayoutVersion = "2.1.4"
core = "1.6.1"
coreTesting = "2.2.0"
espressoContrib = "3.6.1"
espressoCoreVersion = "3.5.1"
firebaseBom = "33.8.0"
googlePlayServicesLocation = "21.0.1"
hamcrestLibrary = "2.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
googleGmsGoogleServices = "4.4.2"
firebaseDatabase = "21.0.0"
mockitoAndroid = "5.11.0"
mockitoAndroidVersion = "4.5.1"
mockitoCore = "4.11.0"
mockitoCoreVersion = "4.0.0"
mockitoInline = "4.0.0"
firebase-auth = "22.3.0"
google-services = "4.4.0"
mockitoInlineVersion = "4.5.1"
mockitoMockitoAndroid = "5.3.1"
mockitoMockitoCore = "5.11.0"
mockitoMockitoCoreVersion = "4.5.1"
orgMockitoMockitoCore = "5.3.1"
places = "4.1.0"
playServicesMaps = "19.1.0"
rules = "1.6.1"
rulesVersion = "1.6.1"
runner = "1.6.2"
playServicesLocation = "21.3.0"
runnerVersion = "1.6.2"
uiautomator = "2.3.0"
firebaseMessaging = "24.1.1"

[libraries]

android-maps-utils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
core = { module = "androidx.test:core", version.ref = "core" }
espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espressoContrib" }
espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoContrib" }
ext-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "androidxJunitVersion" }
gms-play-services-location-v2101 = { module = "com.google.android.gms:play-services-location", version.ref = "googlePlayServicesLocation" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrestLibrary" }
mockito-android-v451 = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroidVersion" }
mockito-android-v531 = { module = "org.mockito:mockito-android", version.ref = "mockitoMockitoAndroid" }
mockito-core-v451 = { module = "org.mockito:mockito-core", version.ref = "mockitoMockitoCoreVersion" }
mockito-core-v531 = { module = "org.mockito:mockito-core", version.ref = "orgMockitoMockitoCore" }
mockito-inline-v451 = { module = "org.mockito:mockito-inline", version.ref = "mockitoInlineVersion" }
places = { module = "com.google.android.libraries.places:places", version.ref = "places" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
rules = { group = "androidx.test", name = "rules", version = "1.5.0" }
rules-v161 = { module = "androidx.test:rules", version.ref = "rulesVersion" }
runner = { group = "androidx.test", name = "runner", version = "1.5.2" }

constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-core-v400 = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-core-v5110 = { module = "org.mockito:mockito-core", version.ref = "mockitoMockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
runner-v162 = { module = "androidx.test:runner", version.ref = "runnerVersion" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

